version: '2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: time_keeper
    ports:
      - '5432:5432'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    image: innocentzero/ruby:2.3.1
    ports:
      - '3000:3000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
