require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WorkPatternsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WorkPattern. As you add validations to WorkPattern, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkPatternsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all work_patterns as @work_patterns" do
      work_pattern = WorkPattern.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:work_patterns)).to eq([work_pattern])
    end
  end

  describe "GET #show" do
    it "assigns the requested work_pattern as @work_pattern" do
      work_pattern = WorkPattern.create! valid_attributes
      get :show, params: {id: work_pattern.to_param}, session: valid_session
      expect(assigns(:work_pattern)).to eq(work_pattern)
    end
  end

  describe "GET #new" do
    it "assigns a new work_pattern as @work_pattern" do
      get :new, params: {}, session: valid_session
      expect(assigns(:work_pattern)).to be_a_new(WorkPattern)
    end
  end

  describe "GET #edit" do
    it "assigns the requested work_pattern as @work_pattern" do
      work_pattern = WorkPattern.create! valid_attributes
      get :edit, params: {id: work_pattern.to_param}, session: valid_session
      expect(assigns(:work_pattern)).to eq(work_pattern)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WorkPattern" do
        expect {
          post :create, params: {work_pattern: valid_attributes}, session: valid_session
        }.to change(WorkPattern, :count).by(1)
      end

      it "assigns a newly created work_pattern as @work_pattern" do
        post :create, params: {work_pattern: valid_attributes}, session: valid_session
        expect(assigns(:work_pattern)).to be_a(WorkPattern)
        expect(assigns(:work_pattern)).to be_persisted
      end

      it "redirects to the created work_pattern" do
        post :create, params: {work_pattern: valid_attributes}, session: valid_session
        expect(response).to redirect_to(WorkPattern.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved work_pattern as @work_pattern" do
        post :create, params: {work_pattern: invalid_attributes}, session: valid_session
        expect(assigns(:work_pattern)).to be_a_new(WorkPattern)
      end

      it "re-renders the 'new' template" do
        post :create, params: {work_pattern: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested work_pattern" do
        work_pattern = WorkPattern.create! valid_attributes
        put :update, params: {id: work_pattern.to_param, work_pattern: new_attributes}, session: valid_session
        work_pattern.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested work_pattern as @work_pattern" do
        work_pattern = WorkPattern.create! valid_attributes
        put :update, params: {id: work_pattern.to_param, work_pattern: valid_attributes}, session: valid_session
        expect(assigns(:work_pattern)).to eq(work_pattern)
      end

      it "redirects to the work_pattern" do
        work_pattern = WorkPattern.create! valid_attributes
        put :update, params: {id: work_pattern.to_param, work_pattern: valid_attributes}, session: valid_session
        expect(response).to redirect_to(work_pattern)
      end
    end

    context "with invalid params" do
      it "assigns the work_pattern as @work_pattern" do
        work_pattern = WorkPattern.create! valid_attributes
        put :update, params: {id: work_pattern.to_param, work_pattern: invalid_attributes}, session: valid_session
        expect(assigns(:work_pattern)).to eq(work_pattern)
      end

      it "re-renders the 'edit' template" do
        work_pattern = WorkPattern.create! valid_attributes
        put :update, params: {id: work_pattern.to_param, work_pattern: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested work_pattern" do
      work_pattern = WorkPattern.create! valid_attributes
      expect {
        delete :destroy, params: {id: work_pattern.to_param}, session: valid_session
      }.to change(WorkPattern, :count).by(-1)
    end

    it "redirects to the work_patterns list" do
      work_pattern = WorkPattern.create! valid_attributes
      delete :destroy, params: {id: work_pattern.to_param}, session: valid_session
      expect(response).to redirect_to(work_patterns_url)
    end
  end

end
